export interface Canal {
  id: string;
  nome: string;
  categoria: string;
  cortesia?: boolean;
}

export const canais: Canal[] = [
  // 📺 Canais Abertos Cortesia
  { id: "1", nome: "Band HD", categoria: "Canais Abertos Cortesia" },
  { id: "2", nome: "Cultura HD", categoria: "Canais Abertos Cortesia" },
  { id: "3", nome: "Gazeta HD", categoria: "Canais Abertos Cortesia" },
  { id: "4", nome: "Globo HD", categoria: "Canais Abertos Cortesia" },
  { id: "5", nome: "RECORD HD", categoria: "Canais Abertos Cortesia" },
  { id: "6", nome: "REDE TV HD", categoria: "Canais Abertos Cortesia" },
  { id: "7", nome: "Rede Vida HD", categoria: "Canais Abertos Cortesia" },
  { id: "8", nome: "SBT HD", categoria: "Canais Abertos Cortesia" },

  // 🇧🇷 Canais Obrigatórios Gratuitos
  { id: "9", nome: "TV Brasil HD", categoria: "Canais Obrigatórios Gratuitos" },
  { id: "10", nome: "Canal Comunitário", categoria: "Canais Obrigatórios Gratuitos" },
  { id: "11", nome: "Canal Legislativo", categoria: "Canais Obrigatórios Gratuitos" },
  { id: "12", nome: "Canal Universitário", categoria: "Canais Obrigatórios Gratuitos" },
  { id: "13", nome: "TV Brasil 2", categoria: "Canais Obrigatórios Gratuitos" },
  { id: "14", nome: "TV Câmara", categoria: "Canais Obrigatórios Gratuitos" },
  { id: "15", nome: "TV Escola", categoria: "Canais Obrigatórios Gratuitos" },
  { id: "16", nome: "TV Justiça", categoria: "Canais Obrigatórios Gratuitos" },
  { id: "17", nome: "TV Senado", categoria: "Canais Obrigatórios Gratuitos" },
  { id: "18", nome: "TV Brasil", categoria: "Canais Obrigatórios Gratuitos" },

  // 🌍 Documentários
  { id: "19", nome: "Animal Planet HD", categoria: "Documentários" },
  { id: "20", nome: "Discovery HD", categoria: "Documentários" },
  { id: "21", nome: "Discovery Science HD", categoria: "Documentários" },
  { id: "22", nome: "Discovery Theater HD", categoria: "Documentários" },
  { id: "23", nome: "Discovery Turbo HD", categoria: "Documentários" },
  { id: "24", nome: "Discovery world HD", categoria: "Documentários" },
  { id: "25", nome: "Futura HD", categoria: "Documentários" },
  { id: "26", nome: "History 2 HD", categoria: "Documentários" },
  { id: "27", nome: "History HD", categoria: "Documentários" },
  { id: "28", nome: "National Geographic HD", categoria: "Documentários" },

  // 🎶 Entretenimento Música
  { id: "29", nome: "Trace Brazuca HD", categoria: "Entretenimento Música", cortesia: true },
  { id: "30", nome: "BIS HD", categoria: "Entretenimento Música" },
  { id: "31", nome: "MTV HD", categoria: "Entretenimento Música" },
  { id: "32", nome: "MTV Live HD", categoria: "Entretenimento Música" },
  { id: "33", nome: "Multishow HD", categoria: "Entretenimento Música" },
  { id: "34", nome: "Music Box Brazil HD", categoria: "Entretenimento Música" },
  { id: "35", nome: "TV WA", categoria: "Entretenimento Música" },
  { id: "36", nome: "MTV'S 00", categoria: "Entretenimento Música" },

  // ⚽ Esportes
  { id: "37", nome: "ESPN 5 HD", categoria: "Esportes" },
  { id: "38", nome: "Band Sports HD", categoria: "Esportes" },
  { id: "39", nome: "ESPN 2 HD", categoria: "Esportes" },
  { id: "40", nome: "ESPN 3 HD", categoria: "Esportes" },
  { id: "41", nome: "ESPN 4 HD", categoria: "Esportes" },
  { id: "42", nome: "ESPN HD", categoria: "Esportes" },
  { id: "43", nome: "ESPN 6 HD", categoria: "Esportes" },
  { id: "44", nome: "SporTV 2 HD", categoria: "Esportes" },
  { id: "45", nome: "SporTV 3 HD", categoria: "Esportes" },
  { id: "46", nome: "SporTV HD", categoria: "Esportes" },
  { id: "47", nome: "Paramount+ Conmebol", categoria: "Esportes" },
  { id: "48", nome: "Paramount+ Conmebol 1", categoria: "Esportes" },
  { id: "49", nome: "Paramount+ Conmebol 2", categoria: "Esportes" },
  { id: "50", nome: "Nosso Futebol", categoria: "Esportes" },
  { id: "51", nome: "Nsports", categoria: "Esportes" },
  { id: "52", nome: "Xsports", categoria: "Esportes" },

  // 🎬 Filmes
  { id: "53", nome: "AMC HD", categoria: "Filmes" },
  { id: "54", nome: "Canal Brasil HD", categoria: "Filmes" },
  { id: "55", nome: "Cinemax HD", categoria: "Filmes" },
  { id: "56", nome: "Megapix HD", categoria: "Filmes" },
  { id: "57", nome: "Paramount Network HD", categoria: "Filmes" },
  { id: "58", nome: "Prime Box Brazil HD", categoria: "Filmes" },
  { id: "59", nome: "Space HD", categoria: "Filmes" },
  { id: "60", nome: "Studio Universal HD", categoria: "Filmes" },
  { id: "61", nome: "TCM", categoria: "Filmes" },
  { id: "62", nome: "TNT HD", categoria: "Filmes" },

  // 👶 Infantis
  { id: "63", nome: "Baby TV", categoria: "Infantis" },
  { id: "64", nome: "Cartoon Network HD", categoria: "Infantis" },
  { id: "65", nome: "Cartoonito HD", categoria: "Infantis" },
  { id: "66", nome: "Discovery Kids HD", categoria: "Infantis" },
  { id: "67", nome: "Disney Channel HD", categoria: "Infantis" },
  { id: "68", nome: "Gloob HD", categoria: "Infantis" },
  { id: "69", nome: "Gloobinho HD", categoria: "Infantis" },
  { id: "70", nome: "Nick Jr HD", categoria: "Infantis" },
  { id: "71", nome: "Nickelodeon HD", categoria: "Infantis" },
  { id: "72", nome: "Tooncast", categoria: "Infantis" },
  { id: "73", nome: "TV Rá Tim Bum HD", categoria: "Infantis" },
  { id: "74", nome: "ZooMoo HD", categoria: "Infantis" },

  // Mundo (Internacional)
  { id: "75", nome: "Bloomberg TV", categoria: "Mundo" },
  { id: "76", nome: "CNN International", categoria: "Mundo" },
  { id: "77", nome: "DW-TV", categoria: "Mundo" },
  { id: "78", nome: "NHK World Premium", categoria: "Mundo" },
  { id: "79", nome: "RAI International", categoria: "Mundo" },
  { id: "80", nome: "SIC International", categoria: "Mundo" },
  { id: "81", nome: "TV5 Monde", categoria: "Mundo" },
  { id: "82", nome: "TVE International", categoria: "Mundo" },

  // 📰 Notícias
  { id: "83", nome: "Eurochannel HD", categoria: "Notícias", cortesia: true },
  { id: "84", nome: "JP News HD", categoria: "Notícias", cortesia: true },
  { id: "85", nome: "Agro Mais HD", categoria: "Notícias" },
  { id: "86", nome: "Band News HD", categoria: "Notícias" },
  { id: "87", nome: "CNN Brasil HD", categoria: "Notícias" },
  { id: "88", nome: "France 24 HD", categoria: "Notícias" },
  { id: "89", nome: "GloboNews HD", categoria: "Notícias" },
  { id: "90", nome: "Record News", categoria: "Notícias" },
  { id: "91", nome: "BBC World News", categoria: "Notícias" },
  { id: "92", nome: "TV Korea", categoria: "Notícias" },
  { id: "93", nome: "CNN Brasil Money", categoria: "Notícias" },
  { id: "94", nome: "Canal UOL", categoria: "Notícias" },

  // 🎭 Séries
  { id: "95", nome: "A&E HD", categoria: "Séries" },
  { id: "96", nome: "AXN HD", categoria: "Séries" },
  { id: "97", nome: "Comedy Central HD", categoria: "Séries" },
  { id: "98", nome: "FX HD", categoria: "Séries" },
  { id: "99", nome: "ID HD", categoria: "Séries" },
  { id: "100", nome: "Lifetime HD", categoria: "Séries" },
  { id: "101", nome: "Sony HD", categoria: "Séries" },
  { id: "102", nome: "STAR CHANNEL HD", categoria: "Séries" },
  { id: "103", nome: "USA HD", categoria: "Séries" },
  { id: "104", nome: "TNT Novelas", categoria: "Séries" },
  { id: "105", nome: "TNT SERIES HD", categoria: "Séries" },
  { id: "106", nome: "Universal TV HD", categoria: "Séries" },
  { id: "107", nome: "Warner Channel HD", categoria: "Séries" },

  // 🌟 Variedades
  { id: "108", nome: "Fashion TV HD", categoria: "Variedades", cortesia: true },
  { id: "109", nome: "Fish TV HD", categoria: "Variedades", cortesia: true },
  { id: "110", nome: "Mega TV HD", categoria: "Variedades", cortesia: true },
  { id: "111", nome: "Rede Gospel HD", categoria: "Variedades", cortesia: true },
  { id: "112", nome: "Travel Box Brazil HD", categoria: "Variedades", cortesia: true },
  { id: "113", nome: "Canal do Boi HD", categoria: "Variedades", cortesia: true },
  { id: "114", nome: "TV Pai Eterno HD", categoria: "Variedades", cortesia: true },
  { id: "115", nome: "Boa Vontade TV", categoria: "Variedades", cortesia: true },
  { id: "116", nome: "Canal Rural", categoria: "Variedades", cortesia: true },
  { id: "117", nome: "CGTN", categoria: "Variedades", cortesia: true },
  { id: "118", nome: "Polishop TV", categoria: "Variedades", cortesia: true },
  { id: "119", nome: "Rede 21", categoria: "Variedades", cortesia: true },
  { id: "120", nome: "Rede Vida", categoria: "Variedades", cortesia: true },
  { id: "121", nome: "Rit TV", categoria: "Variedades", cortesia: true },
  { id: "122", nome: "Terra Viva", categoria: "Variedades", cortesia: true },
  { id: "123", nome: "TV Aparecida", categoria: "Variedades", cortesia: true },
  { id: "124", nome: "Arte 1 HD", categoria: "Variedades" },
  { id: "125", nome: "Cinecanal HD", categoria: "Variedades" },
  { id: "126", nome: "Curta! HD", categoria: "Variedades" },
  { id: "127", nome: "Discovery Home & Health HD", categoria: "Variedades" },
  { id: "128", nome: "E! HD", categoria: "Variedades" },
  { id: "129", nome: "Film&Arts HD", categoria: "Variedades" },
  { id: "130", nome: "FOOD NETWORK HD", categoria: "Variedades" },
  { id: "131", nome: "GNT HD", categoria: "Variedades" },
  { id: "132", nome: "HGTV HD", categoria: "Variedades" },
  { id: "133", nome: "LIKE HD", categoria: "Variedades" },
  { id: "134", nome: "Modo Viagem HD", categoria: "Variedades" },
  { id: "135", nome: "Off HD", categoria: "Variedades" },
  { id: "136", nome: "Sabor & Arte HD", categoria: "Variedades" },
  { id: "137", nome: "TLC HD", categoria: "Variedades" },
  { id: "138", nome: "Viva HD", categoria: "Variedades" },
  { id: "139", nome: "Woohoo HD", categoria: "Variedades" },
  { id: "140", nome: "Empreender HD", categoria: "Variedades" },
  { id: "141", nome: "Rede Brasil", categoria: "Variedades" },
  { id: "142", nome: "TV Novo Tempo HD", categoria: "Variedades" },
  { id: "143", nome: "SBN", categoria: "Variedades" },
  { id: "144", nome: "Canção Nova", categoria: "Variedades" },
  { id: "145", nome: "Ideal TV", categoria: "Variedades" },
  { id: "146", nome: "Market HD", categoria: "Variedades" },
  { id: "147", nome: "LMC+ HD", categoria: "Variedades" },
  { id: "148", nome: "TBC", categoria: "Variedades" },
];

export const categorias = [
  "Canais Abertos Cortesia",
  "Canais Obrigatórios Gratuitos",
  "Documentários",
  "Entretenimento Música",
  "Esportes",
  "Filmes",
  "Infantis",
  "Mundo",
  "Notícias",
  "Séries",
  "Variedades",
];
